### ISSUE TITLE
This line works when echoing the output to stdout but not with redirect to file. Resulting file contains malformed JSON.

### ISSUE THREAD

**Issue by M015T** [munkireport/caching#1]
This may have worked correctly prior to Mojave but now is a problem.

https://github.com/munkireport/caching/blob/742eab226d917b7e283b5993afe48fdf245eacc0/scripts/caching#L57

**Comment by M015T** [comment]
swapped printf for echo and it worked correctly

`printf "${CACHINGOUTPUT//\}\}]{\"results\":\{/,\"rundate\":$DATE,\"exact_metrics\":${EXACT_METRICS},}" > /usr/local/munki/preflight.d/cache/caching.txt`

**Comment by tuxudo** [comment]
Closed with latest release
