### ISSUE TITLE
array offset caching_model line 265

### ISSUE THREAD

**Issue by precursorca** [munkireport/caching#5]
After switching to php 7.4 I see this error a lot:

`PHP Notice:  Trying to access array offset on value of type null in /Users/Shared/munkireport-php/vendor/munkireport/caching/caching_model.php on line 265`

**Comment by tuxudo** [comment]
This should be resolved as of v1.7 of the module.

**Comment by tuxudo** [comment]
Additional fixes included in v1.8 of the module.
